# Generated by Django 5.0.14 on 2026-02-03 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("snoozed", "Snoozed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        help_text="When the task is due/should be reminded"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                (
                    "source_message",
                    models.TextField(
                        help_text="Original user message that created this task"
                    ),
                ),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "reminder_count",
                    models.IntegerField(
                        default=0, help_text="Number of times user has been reminded"
                    ),
                ),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(
                        blank=True, help_text="Cron-like pattern", max_length=100
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("phone_call", "Phone Call"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("message_content", models.TextField()),
                ("error_message", models.TextField(blank=True)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                ("twilio_call_sid", models.CharField(blank=True, max_length=100)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "db_table": "reminders",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("voice", "Voice"),
                            ("image", "Image"),
                            ("command", "Command"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "ai_intent",
                    models.CharField(
                        blank=True, help_text="Extracted intent from AI", max_length=100
                    ),
                ),
                (
                    "ai_response",
                    models.TextField(blank=True, help_text="AI's generated response"),
                ),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("routine", "Routine"),
                            ("preference", "Preference"),
                            ("location", "Location"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_contexts",
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "status"], name="tasks_user_id_a53e17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "due_at"], name="tasks_user_id_4cbf62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "due_at"], name="tasks_status_899663_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["task", "channel"], name="reminders_task_id_54d15e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["status", "scheduled_at"], name="reminders_status_2cab16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationlog",
            index=models.Index(
                fields=["user", "created_at"], name="conversatio_user_id_33b9d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationlog",
            index=models.Index(fields=["task"], name="conversatio_task_id_4654d9_idx"),
        ),
        migrations.AddIndex(
            model_name="usercontext",
            index=models.Index(
                fields=["user", "context_type"], name="user_contex_user_id_97a7a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercontext",
            index=models.Index(
                fields=["user", "key"], name="user_contex_user_id_3fa94d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercontext",
            unique_together={("user", "context_type", "key")},
        ),
    ]
