# Generated by Django 5.0.14 on 2026-02-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='batch_id',
            field=models.UUIDField(blank=True, help_text='Groups tasks created together', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='location_address',
            field=models.TextField(blank=True, help_text='Address of the location'),
        ),
        migrations.AddField(
            model_name='task',
            name='location_data',
            field=models.JSONField(blank=True, help_text='Rich place details from Places API', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='location_name',
            field=models.CharField(blank=True, help_text="Name of the place (e.g., 'Café Javas')", max_length=255),
        ),
    ]
